### ISSUE TITLE
What to do if the script runThis.sh always asks for the pasword

### ISSUE THREAD

**Issue by ironmaniiith** [ironmaniiith/Github-profile-name-writer#2]
Well if you have added an https url of you git repository, then running the script "runThis.sh" will always ask you for your username and password for pushing the commit, in that case, follow this steps.
#### Assumptions
- Your github username is ironman
- Your github password is password123
- Your github repository name is testrepo

Now run these commands in your repository folder
1. git remote rm origin
2. git remote add origin "https://ironman:password123@github.com/ironman/testrepo.git"

That's it, now run the script and it won't ask for the password...

**Comment by mandarGG** [comment]
Yes it works.Thanks anyway, i was stuck in a loop while running the script
